### ISSUE TITLE
Missing information to get started

### ISSUE THREAD

**Issue by jonathanschneider** [BernhardSchlegel/BierBot#11]
Hi!

I would like to check out BierBot but am missing some information on how to get started after installation. Does it start automatically? Do I have to start something manually? On which port is the web server accessible?

Thanks in advance!

**Comment by jonathanschneider** [comment]
Ok, reading through the files, I realised BierBot is installed as a service and supposed to start on startup. The web server is accessible on port 80. Since I can't access the web server I tried to manually start the service and got this error message:

`Failed to start bierbot.service: Unit bierbot.service is not loaded properly: Invalid argument.`

Any ideas?

**Comment by BernhardSchlegel** [comment]
Hi Jonathan,

thanks for checking out the BierBot. Sorry to hear about your issues. My spontaneous guess would be that something went 
wrong when you pasted the bierbot.service file (some unexpected char, e.g.). In theory I think you are perfectly on track.

To debug I'll need some additional information, however. 

1. What exactly did you type to start the service?
2. Did you try to start the BierBot programm without the service layer `sudo /usr/bin/node /home/pi/BierBot/server/server.js`? Does this work?
3. Does `journalctl -e -u bierbot.service` show any output?

Best,
Bernhard.

**Comment by jonathanschneider** [comment]
I installed BierBot on another Raspberry Pi and there it worked. I can't reproduce the issue and the information I was missing I added with the pull request #13. Let's close it.
