### ISSUE TITLE
Server gives no API Key for Brick's Captive Portal

### ISSUE THREAD

**Issue by michluk** [BernhardSchlegel/BierBot#24]
Hey, 

Somehow, the Bierbot Server (Bricks -> Add Brick) does not give me any API key that is required to be entered into the Brick's Captive Portal. What could be the issue here? II tried several Browsers and different devices, but the result is the same. The field remains empty. See Screenshot.

I don't know if I am missing anything. Thanks in advance!
<img width="559" alt="Bildschirmfoto 2021-10-06 um 01 34 02" src="https://user-images.githubusercontent.com/32687706/136117211-74d61d1b-31f0-4e7b-96d1-d97e2d440f0c.png">

**Comment by BernhardSchlegel** [comment]
Hey Lukas, sorry to hear that. That's both bad and interesting. Please send us an email (hello@bierbot.com) with your registered email and the browser URL when your on the "add bricks" page.

Thanks,
Bernhard.

**Comment by michluk** [comment]
Hi Bernhard,

Thanks for your fast reply. I got a solution to the problem, but maybe the issue is still some kind of bug. 
I noticed, that in the top right corner no brewery was selected. After selecting a Brewery (i.e. the default one), it worked out. 
I do not know, how I was able to have an empty selection in this dropdown...

Interestingly, with this empty selection, the subsections under „Brewery“ in the left menu where only „Administration“, „Bricks“ and „Equipment“. With the correct dropdown value, the list expanded to the full 7 menu sub-points. Maybe this could be a bug?

Regards,
Lukas

-----------

The field was empty in different Browsers (Safari, Firefox, Chrome on MacOS and Firefox on Ubuntu). Clicking the button „Copy“ also gave me no API key. The fields for Tilt and iSpindle were also empty.
I also had the following issue: When trying to create a device (under Equipment), the loading wheel on the button „Create“ rotates and nothing happens after that. Now everything works.

**Comment by BernhardSchlegel** [comment]
Hi Lukas,

pretty cool you figured it out! That sounds indeed like a bug! Technically speaking: I assume a race condition somewhere in the user creation logic (user creation does not wait for user creation). If you want, send us a feedback using the blue feedback button in the lower right corner. That would help us to investigate further!

Happy brewing,
Bernhard.

**Comment by michluk** [comment]
Hi Bernhard,

Of course I would like to help you by sending feedback. But does this make any sense by now? I cannot "delect" the Brewery anymore - the dropdown does not allow me to chose "empty". So the error is not reproducible by me anymore (or at least I don't know how :-D ).

Regards
Lukas

**Comment by BernhardSchlegel** [comment]
I can check the server logs when your user was created 👍  so "maybe" (20% chance) - I'll leave it up to you!

**Comment by michluk** [comment]
I sent the data as requested through the feedback function!

Thanks
