### ISSUE TITLE
ReferenceError: defaults is not defined

### ISSUE THREAD

**Issue by befel** [BernhardSchlegel/BierBot#8]
Hi, great project!
I would like to try it out, but get a ReferenceError in server.js at line 271.
I followed your howto on a Pi2 B (fresh installation)

**Comment by BernhardSchlegel** [comment]
Hi befel, thanks for checking out the Bierbot. Sorry to hear you're experiencing troubles. Was your Raspian a fresh install? Can you share the complete error message?

Best,
Bernhard.

**Comment by BernhardSchlegel** [comment]
Hi, 

found it! For some strange reason your setup failed. Can you try adding the following line as line 40 in server.js?

`var defaults = require('./libs/defaults');`

Something went wrong during setup..

**Comment by befel** [comment]
Yes thanks, That was the problem. It's working now...time to play :)
Yes fresh Raspbian install

**Comment by BernhardSchlegel** [comment]
Glad to hear! Thanks for participating :)
